site_name: HassakuLab Knowledges
site_url: https://knowledge.hassakulab.com/
site_description: knowledges for creation
theme:
  name: material
  language: ja
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: light green
      accent: orange
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: light green
      accent: orange
  features:
      - navigation.instant
      - navigation.tabs
      - navigation.tabs.sticky
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/logo.png

extra:
  social:
    - icon: material/home
      link: https://hassakulab.com
    - icon: material/twitter
      link: https://twitter.com/HassakuTb
      name: author on twitter

extra_css:
  - "css/custom.css"

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - footnotes

copyright: Copyright &copy; 2021-2022 HassakuLab

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages
