name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: python -m pip install mkdocs
      - run: python -m pip install mkdocs-material
      - run: python -m pip install mkdocs-git-revision-date-localized-plugin
      - run: python -m pip install mkdocs-awesome-pages-plugin

      - name: Build
        run: python -m mkdocs build
        
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
